FROM node:18 AS base
WORKDIR /app

COPY package*.json ./

FROM base AS development
ENV NODE_ENV=development
RUN npm install
COPY . .

RUN npm run build
RUN npm run migration:run

CMD ["npm", "run", "start:dev"]