FROM node:20-alpine

ENV NODE_ENV production

USER node
WORKDIR /home/node

COPY package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN npm run build \
    && npm prune --omit=dev

RUN npm run migration:run

CMD ["node", "dist/main.js"]